### ISSUE TITLE
Which kind of projects are considered "real"?

### ISSUE THREAD

**Issue by mkermani144** [jeromedalbert/real-world-react#5]
Although there are some details about the term "real" in README file, it is not clear for me that which kind of projects are considered real. For example, I don't know if my app, [Wanna](https://github.com/mkermani144/wanna), is a kind of so-called _real_ React project. Can anyone provide a more exact definition of the word? :)

**Comment by jeromedalbert** [comment]
For now small projects may be a fit because this repo only has 47 projects. Compare that to [real-world-rails](https://github.com/eliotsykes/real-world-rails) which has 167 of them. 😄 

In the future, if the number of projects grow, I may be more strict and remove smaller projects from the list.

In the meantime, your project may apply, although I was unable to test it on my Mac so I can't judge. Maybe submit a PR when you support Mac desktop or web.
